# Fifty NumPy Attributes and Functions

In [3]:
import numpy as np
(np.__version__)

'1.19.3'

In [ ]:
# Creating nd Array:

In [2]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b = np.arange(21)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [4]:
c = np.random.randn(11)
c

array([-0.81373602, -1.67115129, -1.31269906,  0.53562124, -0.94585615,
       -0.27507478, -0.19173565,  0.25348287,  0.93497835,  0.98043384,
       -0.25631289])

In [10]:
d = np.array([
    [1.0,2.0,3.0],
    [4.0,5.0,6.0],
    ])
d

array([[1., 2., 3.],
       [4., 5., 6.]])

In [14]:
# Checking the data types of the arrays:
a.dtype
b.dtype




dtype('int32')

In [16]:
c.dtype
d.dtype

dtype('float64')

# Arithematic Operations on the array:

In [17]:
e = range(100000)
e

range(0, 100000)

In [20]:
e1 = np.arange(100)
e1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [21]:
%time for i in range(1,11): result = [x*2 for x in e]

Wall time: 1.02 ms


In [24]:
%time for i in range(1,11): result1 = e1 * 2
          
          
    

Wall time: 0 ns


In [25]:
# Addition
F = np.arange(1,11)
F

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
r = F + 5 ; r

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [27]:
# Subtraction:
r1 = F - 3 ; r1


array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [29]:
# Multiplication:
r2 = F * 3 ; r2

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [30]:
# Division:
r3 = F/ 4; r3

array([0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ])

In [31]:
# Power:
r4 = F ** 2 ; r4

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [32]:
g = np.random.rand(5)
g>0

array([ True,  True,  True,  True,  True])

In [33]:
g<0

array([False, False, False, False, False])

In [41]:
l1 = np.arange(1,28)
l1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [42]:
l1.shape

(27,)

In [44]:
l1 = np.zeros((27))

In [45]:
l1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Checking that the array elements is finite or not:


In [53]:
m = np.array([1,2,3,np.inf,np.nan,5])
print(" Real Array is given below:\n",m)
print(" Now checking the required solution.\n",np.isfinite(m))


 Real Array is given below:
 [ 1.  2.  3. inf nan  5.]
 Now checking the required solution.
 [ True  True  True False False  True]


### Checking the any of the elements of a given array is zero or not:

In [51]:
z = np.array([0,0,1,0,2,0])
print("Array is =",z)
print(" Testing the condition:\n",np.any(z))

z1 = np.array([0,0,0,0,0])
print("Array is =",z1)
print(" Testing the condition:\n",np.any(z1))


Array is = [0 0 1 0 2 0]
 Testing the condition:
 True
Array is = [0 0 0 0 0]
 Testing the condition:
 False


### Checking that none of the elements of the array is zero or not:

In [50]:
y = np.array([1,3,5,7])
print("Array is =",y)
print(" Testing the condition:\n",np.all(y))

y1 = np.array([1,3,5,0,9])
print("Array is =",y1)
print(" Testing the condition:\n",np.all(y1))


Array is = [1 3 5 7]
 Testing the condition:
 True
Array is = [1 3 5 7]
 Testing the condition:
 False


### Checking that the elements of the array are real numbers or complex numbers:

In [55]:
a = np.array([11, 13, 15+0j, 17, 19+1j,20, 8+4j,5j])
print("The given array is = ",a)
print(" Checking for the real numbers:\n",np.isreal(a))
print(" Checking for the complex numbers:\n",np.iscomplex(a))



The given array is =  [11.+0.j 13.+0.j 15.+0.j 17.+0.j 19.+1.j 20.+0.j  8.+4.j  0.+5.j]
 Checking for the real numbers:
 [ True  True  True  True False  True False False]
 Checking for the complex numbers:
 [False False False False  True False  True  True]


In [14]:
# Obtaining Odd numbers from the array:
oddnumber = np.array([1,11,2,3,4,5,6,7,8,9,10])
oddnumber[oddnumber %2 == 1]


array([ 1, 11,  3,  5,  7,  9])

In [15]:
# Obtaining Even numbers from the array:
Evennumber = np.array([1,11,2,3,4,5,6,7,8,9,10])
Evennumber[Evennumber %2 == 0]


array([ 2,  4,  6,  8, 10])

In [20]:
# Full Method:
np.full((2,2,3),False,dtype = bool)

array([[[False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False]]])

In [25]:
# Reshape :

array = np.arange(10)
array.reshape(2,-11)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [33]:
a = np.array([1,3,5,7,9,10,12,13,16,14,15])
b = np.array([2,4,6,8,10,12,15,18,19,20,122])
len(a)
len(b)


11

In [37]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [40]:
rand_arr = np.random.randint(low = 3, high = 6, size = (4,3)) + np.random.random((4,3))
rand_arr

array([[5.61183809, 5.91328495, 5.70237589],
       [5.29889993, 5.7724157 , 5.84431284],
       [3.25697495, 3.0354559 , 3.65508011],
       [3.30002871, 5.84234216, 3.52714467]])

In [45]:
# Reverse the rows of a 2D array:
Arr = np.arange(9).reshape(3,3)
Arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [48]:
# Reverse the coloumns of a 2D array:
ARRAY = np.arange(9).reshape(3,3)
ARRAY[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [55]:
c = np.arange(9)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [56]:
c.shape

(9,)

In [58]:
c.reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [67]:
# Extraction of numbers between a range from numpy array:
a = np.array([2,1,3,4,6,8,10,12,13,5,6,7])
index = np.where((a>=5) & (a<=10))
a[index]

array([ 6,  8, 10,  5,  6,  7])

In [70]:
# Remove that elements from one array which are same in other array:
x = np.array([12,13,14,15,16,18])
y = np.array([1,13,2,15,6,7])
np.setdiff1d(y,x)

array([1, 2, 6, 7])

In [71]:
# Common elements between two arrays:
x = np.array([12,13,14,15,16,18,7,8,20,19])
y = np.array([1,13,2,15,6,7,9,11,18,14])
np.intersect1d(x,y)

array([ 7, 13, 14, 15, 18])

In [80]:
# Stack Two Array Vertically:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
np.concatenate([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [81]:
# Stack Two Array Horizontally:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
np.concatenate([a,b],axis = 1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])